version: '1.0'
name: douyin-workflow
displayName: 截图上传抖音
triggers:
  trigger: auto
  schedule:
    cron: '0 * * * *'
  push:
    branches:
      - main

stages:
  - stage: build
    name: 构建
    jobs:
      - job: run
        name: 执行脚本
        runs-on: ubuntu
        steps:
          - name: 安装依赖
            shell: bash
            command: |
              pip install -r requirements.txt

          - name: 生成截图并上传
            shell: bash
            command: |
              python3 douyin/main.py
